# Generated by Django 4.2.11 on 2025-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(default='open', max_length=60),
        ),
    ]
