# Generated by Django 4.2.11 on 2025-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
