# Generated by Django 4.2.11 on 2025-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
