# Generated by Django 4.2.11 on 2025-09-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watched',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
