# Generated by Django 4.2.11 on 2025-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watched',
            field=models.CharField(default='yes', max_length=10),
        ),
    ]
